
debug: false
trace: false
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  ssl:
    enabled: false
spring:
  jpa:
    properties:
      hibernate:
        default_schema: excel_bot
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
    open-in-view: true
  flyway:
    baseline-on-migrate: true
    schemas: excel_bot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_env
    username: postgres
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://sso.koinavn.dev/realms/koina-dev/protocol/openid-connect/certs
  jackson:
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 2MB
logging:
  charset:
    file: UTF-8
    console: UTF-8
  logback:
    rollingpolicy:
      clean-history-on-start: false
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 10MB
      max-history: 60
      total-size-cap: 0B
  level:
    root: info
    org.springframework: info
